# Autogenerated wrapper script for QOCO_jll for powerpc64le-linux-gnu
export qoco

JLLWrappers.@generate_wrapper_header("QOCO")
JLLWrappers.@declare_library_product(qoco, "libqoco.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        qoco,
        "lib/libqoco.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
