# Autogenerated wrapper script for QOCO_jll for x86_64-apple-darwin
export qoco

JLLWrappers.@generate_wrapper_header("QOCO")
JLLWrappers.@declare_library_product(qoco, "@rpath/libqoco.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        qoco,
        "lib/libqoco.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
