# Autogenerated wrapper script for QOCO_jll for x86_64-w64-mingw32
export qoco

JLLWrappers.@generate_wrapper_header("QOCO")
JLLWrappers.@declare_library_product(qoco, "libqoco.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        qoco,
        "bin\\libqoco.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
